--HER ILIN EN COK SATAN ILK 5 KATEGORISINI GETIREN SORGUYU YAZINIZ.
SELECT
S.CITY, S1.CATEGORY1, SUM(LINETOTAL) TOTALSALE FROM SALEORDERS S
CROSS APPLY
(SELECT TOP 5 CATEGORY1, SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS 
WHERE CITY = S.CITY 
GROUP BY CATEGORY1 
ORDER BY 2 DESC) S1
GROUP BY S.CITY,S1.CATEGORY1
ORDER BY S.CITY,SUM(S1.TOTALSALE) DESC