--HER ILIN HAFTANIN EN COK HANGI GUNUNDE SATIS YAPTIGINI
--OGRENIP ONA GORE SEHIR VE GUNLERE OZEL KAMPANYA YAPMAK
--ISTIYORUZ. SEHIRLERIN HAFTANIN GUNLERINE GORE NE KADARLIK
--SATIS YAPTIGI BILGISINI GETIREN SORGUYU YAZUNUZ.

SELECT CITY, DAYOFWEEK_, SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS
GROUP BY CITY,DAYOFWEEK_
ORDER BY CITY,DAYOFWEEK_
