SET LANGUAGE Turkish
SELECT TOP 100 
OD.ID,
U.USERNAME_,U.NAMESURNAME,U.TELNR1,U.TELNR2,
C.COUNTRY,CT.CITY,T.TOWN,ADR.ADDRESSTEXT,	
O.ID,ITM.ITEMCODE,ITM.ITEMNAME,ITM.BRAND,ITM.CATEGORY1,
ITM.CATEGORY2,ITM.CATEGORY3,ITM.CATEGORY4,OD.AMOUNT,
OD.UNITPRICE,OD.LINETOTAL, CONVERT(DATE,O.DATE_) AS ORDERDATE,
CONVERT(TIME,O.DATE_) ORDERTIME, YEAR(O.DATE_) AS YEAR_,
DATENAME(MONTH,O.DATE_) AS MONTH_,DATENAME(DW,O.DATE_) AS DAYOFWEEK_
FROM ORDERS O
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
INNER JOIN USERS U ON O.USERID=U.ID
INNER JOIN ADDRESS ADR ON ADR.ID=O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID=ADR.COUNTRYID
INNER JOIN CITIES CT ON CT.ID=ADR.CITYID
INNER JOIN TOWNS T ON T.ID=ADR.TOWNID
ORDER BY OD.ID

SELECT TOP 100 * FROM SALEORDERS

