--SALEORDERS TABLOSU SEHIRLERE GORE HANGI AYDA NE KADARLIK
--SATIS YAPILDIGI BILGISINI CEKEN SQL SORGUSUNU YAZINIZ.

SELECT CITY, MONTH_, SUM(LINETOTAL) AS TOTALSALE
FROM SALEORDERS
GROUP BY CITY, MONTH_
ORDER BY CITY ASC, MONTH_ ASC