--HER ILIN HAFTANIN EN COK HANGI GUNUNDE SATIS YAPTIGINI OGRENIP ONA GORE
--SEHIR VE GUNLERE OZEL KAMPANYA YAPMAK ISTIYORUZ. SEHIRLERIN HAFTANIN
--GUNLERINE GORE NE KADARLIK SATIS YAPTIGI BILGISINI GETIREN SORGUYU YAZ.

SELECT CITY, 
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='01.PZT' ) AS Pazartesi,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='02.SAL' ) AS Salý,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='03.ÇAR' ) AS Çarþamba,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='04.PER' ) AS Perþembe,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='05.CUM' ) AS Cuma,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='06.CMT' ) AS Cumartesi,
(SELECT SUM(LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='07.PAZ' ) AS Pazar
FROM SALEORDERS S
GROUP BY CITY
ORDER BY CITY ASC
