--TMDB SITESINDE HERHANGI BIR FILMIN VERILERINI RESIMDEKI GIBI SORGULAYINIZ.

SELECT TITLE+' ('+CONVERT(VARCHAR,YEAR(RELEASE_DATE))+')' TITLE_,
RELEASE_DATE,
CONVERT(VARCHAR,RUNTIME/60)+'h'+CONVERT(VARCHAR,RUNTIME%60)+'m' DURATION,
VOTE_AVERAGE*10 VOTE_AVERAGE,TAGLINE,OVERVIEW,POSTER_PATH,

--KATEGORILERI TEK SATIRDA YAZDIRMAK ICIN
(SELECT GENRE+',' FROM MOVIE_GENRE MG
INNER JOIN GENRE G ON G.GENREID=MG.GENREID
WHERE MG.FILMID=M.FILMID
FOR XML PATH('')
) GENRES,

--CALISANLARI YAZDIRMAK ISTERSEK
(SELECT (P.NAME_+' ('+J.JOB+')')+',' FROM CREW_CREDIT CC
INNER JOIN DEPARTMENT D ON D.ID=CC.DEPARTMENTID
INNER JOIN JOB J ON J.ID=CC.JOBID
INNER JOIN PERSON P ON P.PERSONID=CC.PERSONID
WHERE FILMID=98 AND J.JOB IN ('Director', 'Screenplay')
FOR XML PATH('')) CREW

FROM MOVIE M
WHERE TITLE LIKE 'Gladiator' AND FILMID=98


