--HER FILM KATEGORISININ EN POPULER 5 FILMINI GETIREN SORGU

SELECT GN.GENRE KATEGORI,CONVERT(VARCHAR,MV.ROWNNR)+'.'+MV.TITLE FILMADI,
MV.POPULARITY POPULARITE FROM GENRE GN
CROSS APPLY
(
SELECT TOP 5
ROW_NUMBER() OVER (ORDER BY POPULARITY DESC) AS ROWNNR,
M.TITLE,M.FILMID,M.POPULARITY,G.GENREID,G.GENRE FROM MOVIE_GENRE MG
INNER JOIN GENRE G ON G.GENREID=MG.GENREID
INNER JOIN MOVIE M ON M.FILMID=MG.FILMID
WHERE G.GENREID=GN.GENREID
ORDER BY M.POPULARITY DESC
) MV