SELECT C.NAME_,COUNT(M.FILMID) AS FILM_SAYISI,
SUM(M.BUDGET) AS TOPLAM_BUTCE,ROUND(AVG(M.BUDGET),0) AS ORTALAMA_BUTCE,
SUM(M.REVENUE) AS TOPLAM_HASILAT,AVG(M.REVENUE) AS ORTALAMA_HASILAT
FROM COLLECTION_ C
INNER JOIN MOVIE M ON M.COLLECTIONID=C.COLLECTIONID
GROUP BY C.NAME_
ORDER BY 5 DESC

