SELECT
C.NAME_ AS SERI_ADI,
(SELECT COUNT(*) FROM MOVIE WHERE COLLECTIONID=C.COLLECTIONID) AS FILM_SAYISI,
(SELECT SUM(BUDGET) FROM MOVIE WHERE COLLECTIONID=C.COLLECTIONID) AS TOPLAM_BUTCE,
(SELECT SUM(REVENUE) FROM MOVIE WHERE COLLECTIONID=C.COLLECTIONID) AS TOPLAM_HASILAT,
(SELECT TOP 1 TRIM(STR(YEAR(RELEASE_DATE)))+'-'+ TITLE+STR(BUDGET) FROM MOVIE WHERE COLLECTIONID=C.COLLECTIONID ORDER BY BUDGET DESC) AS ENCOK_BUTCELI_FILM,
(SELECT TOP 1 TRIM(STR(YEAR(RELEASE_DATE)))+'-'+ TITLE+STR(BUDGET) FROM MOVIE WHERE COLLECTIONID=C.COLLECTIONID ORDER BY BUDGET ASC) AS ENAZ_BUTCELI_FILM,
(SELECT TOP 1 TRIM(STR(YEAR(RELEASE_DATE)))+'-'+ TITLE+STR(REVENUE) FROM MOVIE WHERE COLLECTIONID=C.COLLECTIONID ORDER BY REVENUE DESC) AS ENCOK_HASILATYAPAN_FILM,
(SELECT TOP 1 TRIM(STR(YEAR(RELEASE_DATE)))+'-'+ TITLE+STR(REVENUE) FROM MOVIE WHERE COLLECTIONID=C.COLLECTIONID ORDER BY REVENUE ASC) AS ENAZ_HASILATYAPAN_FILM
FROM COLLECTION_ C
ORDER BY 3 DESC