--AMERIKALI VE JAPON SIRKETLERIN BIRLIKTE YAPIMCILIGINI YAPTIGI FILMLERI GETIREN SORGU
SELECT MC.COUNTRYCODE AS ULKEKODU,C.COUNTRY AS ULKEADI,
M.TITLE,M.ORIGINAL_TITLE
FROM MOVIE_COUNTRY MC
INNER JOIN MOVIE M ON M.FILMID=MC.FILMID
INNER JOIN COUNTRY C ON C.CODE=MC.COUNTRYCODE
WHERE C.CODE='US'

AND M.FILMID IN (SELECT FILMID FROM MOVIE_COUNTRY WHERE COUNTRYCODE='JP')