--KARAKTER HAKKINDA BILGI
SELECT NAME_,BIRTHDAY,
(DATEDIFF(DAY,BIRTHDAY,GETDATE())/365) AGE,BIOGRAPHY,ALSO_KNOWN_AS,
CASE WHEN GENDER=2 THEN 'MALE'
	 WHEN GENDER=1 THEN 'FEMALE'
END AS GENDER,
PLACE_OF_BIRTH,COUNTRY,
PROFILE_PATH,POPULARITY,
(SELECT COUNT(*) FROM CAST_CREDIT WHERE PERSONID=P.PERSONID) AS CASTCREDITCOUNT,
(SELECT COUNT(*) FROM CREW_CREDIT WHERE PERSONID=P.PERSONID) AS CREWCREDITCOUNT,
*
FROM PERSON P WHERE NAME_ LIKE 'Robert Downey Jr.'

--OYNADIGI FILMLER
SELECT 
'Acting' TYPE_,
YEAR(M.RELEASE_DATE) YEAR_,
M.TITLE,
CC.CHARACTER_
FROM CAST_CREDIT CC
INNER JOIN PERSON P ON P.PERSONID=CC.PERSONID
INNER JOIN MOVIE M ON M.FILMID=CC.FILMID
WHERE P.PERSONID=3223
ORDER BY M.RELEASE_DATE DESC

--PERSONEL ICINDEKI ALDIGI ROLLER
SELECT 
'Acting' TYPE_,
YEAR(M.RELEASE_DATE) YEAR_,
M.TITLE,
D.DEPARTMENT,
J.JOB
FROM CREW_CREDIT CC
INNER JOIN PERSON P ON P.PERSONID=CC.PERSONID
INNER JOIN MOVIE M ON M.FILMID=CC.FILMID
INNER JOIN DEPARTMENT D ON CC.DEPARTMENTID=D.ID
INNER JOIN JOB J ON J.ID=CC.JOBID
WHERE P.PERSONID=3223
ORDER BY D.DEPARTMENT,M.RELEASE_DATE DESC

--EN ÇOK TANINDIGI 10 FILM
SELECT TOP 10
'Acting' TYPE_,
YEAR(M.RELEASE_DATE) YEAR_,
M.TITLE,
CC.CHARACTER_,
M.POPULARITY
FROM CAST_CREDIT CC
INNER JOIN PERSON P ON P.PERSONID=CC.PERSONID
INNER JOIN MOVIE M ON M.FILMID=CC.FILMID
WHERE P.PERSONID=3223
ORDER BY M.POPULARITY DESC