SELECT P.NAME_ KISI, D.DEPARTMENT BOLUM, J.JOB GOREV,
COUNT(M.FILMID) FILMSAYISI
FROM PERSON P
	INNER JOIN CREW_CREDIT CC ON CC.PERSONID=P.PERSONID
	INNER JOIN DEPARTMENT D ON D.ID=CC.DEPARTMENTID
	INNER JOIN JOB J ON J.ID=CC.JOBID
	INNER JOIN MOVIE M ON M.FILMID=CC.FILMID
WHERE P.NAME_ LIKE 'Quentin Tarantino'
GROUP BY P.NAME_, D.DEPARTMENT, J.JOB
ORDER BY D.DEPARTMENT, J.JOB