CREATE DATABASE HR

USE HR

CREATE TABLE DEPARTMENT(
ID INT IDENTITY(1,1) PRIMARY KEY, DEPARTMENT VARCHAR(50)
)

CREATE TABLE POSITION(
ID INT IDENTITY(1,1) PRIMARY KEY, POSITION VARCHAR(100)
)

CREATE TABLE PERSON(
ID INT IDENTITY(1,1) PRIMARY KEY,
CODE VARCHAR(10),
TCNUMBER VARCHAR(11),
NAME_ VARCHAR(50),
SURNAME VARCHAR(50),
GENDER VARCHAR(1),
BIRTHDATE DATE,
INDATE DATE,
OUTDATE DATE,
DEPARTMENTID INT,
POSITIONID INT,
PARENTPOSITIONID INT,
MANAGERID INT,
TELNR VARCHAR(15),
SALARY FLOAT)
