--Þirketimizde departman bazlý halen çalýþmaya devam eden KADIN ve ERKEK sayýlarý
SELECT DEPARTMENT,
CASE
	WHEN P.GENDER = 'E' THEN 'Erkek'
	WHEN P.GENDER = 'K' THEN 'Kadýn'
END AS GENDER
,COUNT(GENDER) AS PERSONCOUNT FROM PERSON P
INNER JOIN DEPARTMENT D ON D.ID = P.DEPARTMENTID
WHERE OUTDATE IS NULL
GROUP BY DEPARTMENT,GENDER
ORDER BY 1