--Þirketimizde departman bazlý halen çalýþmaya devam eden KADIN ve ERKEK sayýlarý
SELECT DEPARTMENT,
(SELECT COUNT(*) FROM PERSON WHERE DEPARTMENTID = D.ID AND GENDER = 'E' AND OUTDATE IS NULL) AS ERKEKSAYISI,
(SELECT COUNT(*) FROM PERSON WHERE DEPARTMENTID = D.ID AND GENDER = 'K' AND OUTDATE IS NULL) AS KADINSAYISI,
(SELECT COUNT(*) FROM PERSON WHERE DEPARTMENTID = D.ID AND OUTDATE IS NULL) AS TOPLAMSAYI
FROM  DEPARTMENT D
ORDER BY 2
