--Þirketimizin Planlama departmanýna yeni bir þef atamasý yapýldý ve maaþýný belirlemek
--istiyoruz. Planlama departmaný için minimum, maximum ve ortalama þef maaþý getiren sorgu
--(Not: iþten çýkmýþ olan personel maaþlarý da dahildir.)
SELECT 
POS.POSITION,MIN(P.SALARY) AS MIN_SALARY,
MAX(P.SALARY) AS MAX_SALARY,
ROUND(AVG(P.SALARY),0) AS AVG_SALARY
FROM POSITION POS
INNER JOIN PERSON P ON P.POSITIONID=POS.ID
WHERE POS.POSITION='PLANLAMA ÞEFÝ'
GROUP BY POS.POSITION

--SUBQUERY ILE ÇOZUMU
SELECT
POS.POSITION ,
(SELECT MIN(SALARY) FROM PERSON WHERE POSITIONID=POS.ID) AS MIN_SALARY,
(SELECT MAX(SALARY) FROM PERSON WHERE POSITIONID=POS.ID) AS MAX_SALARY,
(SELECT ROUND(AVG(SALARY),0) FROM PERSON WHERE POSITIONID=POS.ID) AS AVG_SALARY
FROM POSITION POS
WHERE POS.POSITION = 'PLANLAMA ÞEFÝ'