--HER BIR POZISYONDA MEVCUT HALDE ÇALIÞANLAR OLARAK KAÇ KÝÞÝ VE ORTLAMA MAAÞLARININ
--NE KADAR OLDUÐUNU LISTELETTIRMEK ISTIYORUZ.

SELECT
POS.POSITION,COUNT(PARENTPOSITIONID) AS PERSONELSAYISI, ROUND(AVG(P.SALARY),0) AS MAAS_ORTALAMASI
FROM POSITION POS
INNER JOIN PERSON P ON P.POSITIONID = POS.ID
GROUP BY POS.POSITION

--SUBQUERY ILE
SELECT POS.POSITION,
(SELECT COUNT(PARENTPOSITIONID) FROM PERSON WHERE POSITIONID=POS.ID) AS PERSONCOUNT,
(SELECT ROUND(AVG(SALARY),0) FROM PERSON WHERE POSITIONID=POS.ID) AS MAAS_ORTALAMASI
FROM POSITION POS
ORDER BY 1