--YILLARA GORE IÞE ALINAN PERSONEL SAYISINI KADIN VE ERKEK BAZINDA LISTELETTIR
SELECT DISTINCT YEAR(P.INDATE),
(SELECT COUNT(*) FROM PERSON WHERE GENDER = 'E' AND YEAR(INDATE)=YEAR(P.INDATE)) AS ERKEK_SAYISI,
(SELECT COUNT(*) FROM PERSON WHERE GENDER = 'K' AND YEAR(INDATE)=YEAR(P.INDATE)) AS KADIN_SAYISI,
(SELECT COUNT(*) FROM PERSON WHERE YEAR(INDATE)=YEAR(P.INDATE)) AS TOPLAMSAYI
FROM PERSON P
ORDER BY 1
