--HER BIR PERSONELIMIZIN NE KADAR ZAMANDIR ÇALIÞTIÐI BÝGÝSÝNÝ ÞEKÝLDEKÝ GÝBÝ AY OLARAK GETÝREN SORGUYU YAZINIZ.
SELECT NAME_+' '+SURNAME AS PERSON, INDATE, OUTDATE,
CASE 
	WHEN OUTDATE IS NOT NULL THEN 'ÝÞTEN AYRILDI'
	ELSE 'DEVAM EDIYOR'
END AS WORKINGSTATUS,
CASE 
	WHEN OUTDATE IS NOT NULL THEN DATEDIFF(MONTH,INDATE,OUTDATE)
	ELSE DATEDIFF(MONTH,INDATE,GETDATE())
END AS WORKINGTIME
FROM PERSON

--IKINCI YOL
SELECT NAME_+' '+SURNAME AS PERSON, 
'DEVAM EDIYOR' AS WORKINGSTATUS,
INDATE, OUTDATE, DATEDIFF(MONTH,INDATE,GETDATE()) AS WORKINGTIME
FROM PERSON WHERE OUTDATE IS NULL
UNION ALL
SELECT NAME_+' '+SURNAME AS PERSON,
'IÞTEN AYRILDI' AS WORKINGSTATUS,
INDATE, OUTDATE,DATEDIFF(MONTH,INDATE,OUTDATE) AS WORKINGTIME
FROM PERSON WHERE OUTDATE IS NOT NULL
ORDER BY WORKINGTIME DESC