--ÞÝRKETÝMÝZ 5.YILINDA ÜSTÜNDE HERKESIN ISMININ VE SOYISMININ BAÞ HARFLERININ BULUNDUÐU BIR AJANDA
--BASTIRILIP ÇALIÞANLARINA HEDIYE EDECEKTIR. BUNUN ICIN HANGI HARF KOMBINASYONUNDAN EN AZ NE KADAR SAYIDA
--AJANDA BASTIRALACAÐI SORUSUNUN CEVABINI GETIREN SORGUYU YAZINIZ.
--NOT:IKI ISIMLI OLANLARIN BIRINCI ISMININ BAÞ HARFI KULLANILACAKTIR.

SELECT SUBSTRING(NAME_,1,1)+'.'+SUBSTRING(SURNAME,1,1) +'.'  AS SHORTNAME,
COUNT(*) AS PERSONCOUNT
FROM PERSON
GROUP BY SUBSTRING(NAME_,1,1)+'.'+SUBSTRING(SURNAME,1,1) +'.'