--MAAÞ ORTALAMASI 5500 TLDEN FAZLA OLAN DEPARTMANLARI LISTELEYECEK SORGU
SELECT DEPARTMENT,AVG(SALARY) AS AVGSALARY
FROM DEPARTMENT D
INNER JOIN PERSON P ON D.ID = P.DEPARTMENTID 
GROUP BY DEPARTMENT
HAVING AVG(SALARY)>5500
ORDER BY 1

--IKINCI YOL
SELECT *,
(SELECT AVG(SALARY) FROM PERSON WHERE PERSON.DEPARTMENTID = DEPARTMENT.ID ) AS	AVGSALARY
FROM DEPARTMENT
WHERE (SELECT AVG(SALARY) FROM PERSON WHERE PERSON.DEPARTMENTID = DEPARTMENT.ID ) > 5500
ORDER BY 1

