--DEPARTMANLARIN ORTALAMA KIDEMINI AY OLARAK HESAPLAMA
SELECT DEPARTMENT, AVG(WORKINGTIME)
FROM
(
SELECT D.DEPARTMENT,
CASE WHEN OUTDATE IS NULL THEN DATEDIFF(MONTH,INDATE,GETDATE())
ELSE DATEDIFF(MONTH,INDATE,OUTDATE) END AS WORKINGTIME
FROM PERSON P 
INNER JOIN DEPARTMENT D ON D.ID=P.DEPARTMENTID
) T GROUP BY DEPARTMENT
ORDER BY 1