--ARAC MARKALARINA GORE HER MARKADAN NE KADAR ARAC OLDUGU VE YUZDESEL OLARAK
--TOPLAMIN NE KADARINA TEKABUL ETTIGI BILGISINI GETIREN SORGU

SELECT BRAND,COUNT(*) AS COUNT_,
ROUND(CONVERT(FLOAT,COUNT(*))/(SELECT COUNT(*) FROM WEBOFFERS)*100,2) AS PERCENT_
FROM WEBOFFERS
GROUP BY BRAND
ORDER BY 2 DESC