--ISTANBUL'DA VOLKSWAGEN PASSAT MARKA BIR ARAC ARIYORUZ.
--KRITERLERIMIZ SU SEKILDE
--KIMDEN:SAHIBINDEN
--MODEL:2014-2018 ARASI
--VITES:OTOMATIK
--YAKIT:DIZEL
--SIRALAMA:KILOMETRE VE FIYATA GORE

SELECT CITY, TOWN, DISTRICT, TITLE, BRAND, MODEL, KM, 
PRICE,SHIFTTYPE,FUEL,COLOR,YEAR_, FROMWHO
FROM WEBOFFERS W
INNER JOIN CITY C ON C.ID = W.CITYID
INNER JOIN TOWN T ON T.ID = W.TOWNID
INNER JOIN DISTRICT D ON D.ID = W.DISTRICTID
WHERE CITY = 'ÝSTANBUL' AND
BRAND = 'Volkswagen' AND MODEL = 'Passat' AND YEAR_ BETWEEN 2014 AND 2018 AND
FUEL = 'Dizel' AND SHIFTTYPE = 'Otomatik Vites' AND FROMWHO = 'Sahibinden'
ORDER BY 
KM ASC, PRICE