--BMW MARKA ARACLARI ANKARA,ISTANBUL VE IZMIR'DE LISTELETTIREN SORGUYU YAZ
--BURADA SORGUYA GONDERILEN SEHIR ISIMLERI TEKER TEKER DEGIL VIRGUL ILE
--BIRLESTIRELEREK GONDERILECEK
--'ANKARA,ISTANBUL,IZMIR' SEKILDEKI GIBI.

SELECT CITY, TOWN, DISTRICT, TITLE, BRAND, MODEL, KM, 
PRICE,SHIFTTYPE,FUEL,COLOR,YEAR_, FROMWHO
FROM WEBOFFERS W
INNER JOIN CITY C ON C.ID = W.CITYID
INNER JOIN TOWN T ON T.ID = W.TOWNID
INNER JOIN DISTRICT D ON D.ID = W.DISTRICTID
WHERE C.CITY IN (SELECT VALUE FROM string_split('ANKARA,ÝSTANBUL,ÝZMÝR',','))
AND BRAND = 'BMW' 
AND W.COLOR IN (SELECT VALUE FROM string_split('SÝYAH,FÜME,BEYAZ,GRÝ',','))
ORDER BY 
KM ASC, PRICE


