--HANGI SEHIRDE NE KADAR ARAC ILANI OLDUGU BILGISINI GETIREN SORGUYU YAZ
SELECT CITY,COUNT(*) AS COUNT_ FROM WEBOFFERS W
INNER JOIN CITY C ON C.ID = W.CITYID
GROUP BY CITY
ORDER BY 2 DESC

--SUBQUERY ILE
SELECT CITY,
(SELECT COUNT(*) FROM WEBOFFERS WHERE CITYID = C.ID) AS COUNT_
FROM CITY C
ORDER BY 2 DESC