-- URUN KATEGORILERINE GORE SIPARIS DAGILIMI

SELECT 
ITM.CATEGORY1, ITM.CATEGORY2, ITM.CATEGORY3, ITM.CATEGORY4,
SUM(OD.LINETOTAL) as TOTALPRICE, SUM(OD.AMOUNT) AS TOTALAMOUNT, 
COUNT(OD.ID) AS COUNT, (SUM(OD.LINETOTAL) / SUM(OD.AMOUNT)) AS AVGUNITPRICE

FROM ORDERS O
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN CITIES C ON C.ID = A.CITYID
INNER JOIN COUNTRIES CT ON CT.ID = A.COUNTRYID
INNER JOIN INVOICES I ON I.ORDERID = O.ID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
INNER JOIN USERS U ON U.ID = O.USERID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

GROUP BY ITM.CATEGORY1, ITM.CATEGORY2, ITM.CATEGORY3, ITM.CATEGORY4
ORDER BY ITM.CATEGORY1, ITM.CATEGORY2, ITM.CATEGORY3, ITM.CATEGORY4