-- KULLANICI ADI, AD SOYAD, IL, ILCE, SEMT, ACIK ADRES,
-- SIPARIS ID, TARIH, TOPLAM TUTAR, ODEME TARIHI, 
-- BANKA ONAY KODU, FATURA TARIHI, KARGO FIS NO

SELECT 
U.USERNAME_ AS KULLANICIADI,
U.NAMESURNAME AS ADSOYAD,
C.CITY AS IL,
T.TOWN AS ILCE,
D.DISTRICT AS SEMT,
A.ADDRESSTEXT AS ACIKADRES,
O.ID AS SIPARISID,
O.DATE_ AS TARIH,
O.TOTALPRICE AS TOPLAMTUTAR,
P.DATE_ AS ODEMETARIHI,
P.APPROVECODE AS BANKAONAYKODU,
I.DATE_ AS FATURATARIHI,
I.ADDRESSID AS KARGOFISNO

FROM ORDERS O
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN CITIES C ON C.ID = A.CITYID
INNER JOIN COUNTRIES CT ON CT.ID = A.COUNTRYID
INNER JOIN INVOICES I ON I.ORDERID = O.ID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
INNER JOIN USERS U ON U.ID = O.USERID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

