--MAÐAZALARIN AYLARA GÖRE SATIÞ RAKAMLARINI GETIRME
--ÖNCE GÜNCELLEME YAPIYORUZ
UPDATE SALES SET MONTHNAME_ = '01.OCAK' WHERE DATEPART(MONTH,DATE2_) = 1
UPDATE SALES SET MONTHNAME_ = '02.SUBAT' WHERE DATEPART(MONTH,DATE2_) = 2
UPDATE SALES SET MONTHNAME_ = '03.MART' WHERE DATEPART(MONTH,DATE2_) = 3
UPDATE SALES SET MONTHNAME_ = '04.NISAN' WHERE DATEPART(MONTH,DATE2_) = 4
UPDATE SALES SET MONTHNAME_ = '05.MAYIS' WHERE DATEPART(MONTH,DATE2_) = 5
UPDATE SALES SET MONTHNAME_ = '06.HAZIRAN' WHERE DATEPART(MONTH,DATE2_) = 6
UPDATE SALES SET MONTHNAME_ = '07.TEMMUZ' WHERE DATEPART(MONTH,DATE2_) = 7
UPDATE SALES SET MONTHNAME_ = '08.AGUSTOS' WHERE DATEPART(MONTH,DATE2_) = 8
UPDATE SALES SET MONTHNAME_ = '09.EYLUL' WHERE DATEPART(MONTH,DATE2_) = 9
UPDATE SALES SET MONTHNAME_ = '10.EKIM' WHERE DATEPART(MONTH,DATE2_) = 10
UPDATE SALES SET MONTHNAME_ = '11.KASIM' WHERE DATEPART(MONTH,DATE2_) = 11
UPDATE SALES SET MONTHNAME_ = '12.ARALIK' WHERE DATEPART(MONTH,DATE2_) = 12

SELECT MONTHNAME_,CITY, ROUND(SUM(TOTALPRICE),0) AS SUM FROM SALES
GROUP BY MONTHNAME_,CITY
ORDER BY 1,2


