--ANKARA ÞEHRININ GUNLERE GORE TOPLAM SATISLARI
SELECT DATE2_,ROUND(SUM(TOTALPRICE),0) AS TOPLAMSATIS FROM SALES 
WHERE CITY = 'ANKARA'
GROUP BY DATE2_
ORDER BY DATE2_

-- 1.KISIM YENI BIR DEGISKEN OLUSTURDUK VE BU DEGISKENI GUNCELLEDIK
UPDATE SALES SET DATE2_ = CONVERT(DATE,DATE_)