-- BELLI BIR CIRONUN UZERINDE SATIS YAPAN MAGAZALARI GETIRME

SELECT CITY, ROUND(SUM(TOTALPRICE),0) AS TOTALPRICE FROM SALES
GROUP BY CITY
HAVING ROUND(SUM(TOTALPRICE),0) > 100000
ORDER BY 2 DESC